// 不能用namespace，HMRouter无法解析
export class NavParams {
  public static readonly OMC_NAVIGATION_ID: string = 'OmcNavigationId'
  public static readonly HOME_PAGE_URL: string = 'HomePage'
  public static readonly NEW_BEVERAGE_PAGE_URL: string = 'NewBeveragePage'
  public static readonly DAILY_RECORDS_PAGE_URL: string = 'DailyRecordsPage'
  public static readonly RECORD_DETAIL_PAGE_URL: string = 'RecordDetailPage'
}



