export enum BeverageSize {
  // 小杯
  SMALL = "small",
  // 中杯
  MEDIUM = "medium",
  // 大杯
  LARGE = "large",
  // 超大杯
  EXTRA_LARGE = "extra_large"
}

export enum BeverageSweetness {
  // 不额外加糖
  NO_SUGAR = "no_sugar",
  // 三分
  LIGHT_SUGAR = "light_sugar",
  // 五分
  HALF_SUGAR = "half_sugar",
  // 七分
  LESS_SUGAR = "less_sugar",
  // 全糖
  FULL_SUGAR = "full_sugar"
}

export enum BeverageTemperature {
  // 热
  HOT = "hot",
  // 温热
  WARM = "warm",
  // 常温
  NORMAL = "normal",
  // 去冰
  NO_ICE = "no_ice",
  // 少冰
  LESS_COLD = "less_cold",
  // 正常冰
  COLD = "cold"
}
